### ISSUE TITLE
Is this repository going to be maintained?

### ISSUE THREAD

**Issue by nlgranger** [billziss-gh/fusepy#4]
Hello,
It seems fusepy has been mostly unmaintained for a year, is this repository going to be updated more regularly? Do you accept contributions?

**Comment by billziss-gh** [comment]
This is not the main fusepy repository, but only a fork with Windows compatibility. I am happy to accept contributions if you believe that these are relevant to the Windows port. Otherwise it may make more sense to make these contributions to the upstream project.

But, yes, I intend to continue maintaining this fork.

**Comment by nlgranger** [comment]
Nice, thank you.
